"""fixed Job table to have proper foreign keys

Revision ID: 02b17ee9f674
Revises: 2c40294a6045
Create Date: 2023-05-23 11:27:00.448046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02b17ee9f674'
down_revision = '2c40294a6045'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
