"""fixed typo in pets and handler

Revision ID: 170c37e7d2f9
Revises: 02b17ee9f674
Create Date: 2023-05-23 11:29:38.445509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '170c37e7d2f9'
down_revision = '02b17ee9f674'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
