"""removed backref from pets

Revision ID: 8170c2f60a20
Revises: 170c37e7d2f9
Create Date: 2023-05-23 11:34:49.298953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8170c2f60a20'
down_revision = '170c37e7d2f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
